### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/simona#1]
- [x] finish the vignettes
- [x] compare methods
- [x] compare to other tools
- [x] cpp on group sim
- [x] check Sim_SimIC_2010, Sim_XGraSM_2013, Sim_GraSM_2005, Sim_EISI_2015
- [x] test term_sim
